name: Fetch NEPSE Data Daily

on:
  schedule:
    - cron: "30 9 * * 0-5" # At 9:30 AM UTC, Sunday to Friday

  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python main.py

      - name: Commit data
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/
          git commit -m "Add NEPSE data for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push

      - name: Send Discord Notification
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"✅ NEPSE data committed for $(date +'%Y-%m-%d')\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
